/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Asset, AssignmentLog, AuditLog, MaintenanceRecord } from './types';

export const INITIAL_ASSETS: Asset[] = [
  {
    id: 'AST-2026-1001',
    type: 'laptop',
    name: 'MacBook Pro 16"',
    serialNumber: 'C02FX932Q05D',
    brand: 'Apple',
    model: 'M3 Max / 64GB / 2TB',
    os: 'macOS Sequoia 15.1',
    purchaseDate: '2026-01-15',
    purchaseCost: 3499.00,
    department: 'Engineering',
    location: 'San Francisco HQ - Desk 124',
    status: 'checked-out',
    assignedTo: 'Sarah Connor',
    assignedEmail: 'sarah.connor@cyberdyne.co',
    assignedDate: '2026-01-16',
    expectedReturnDate: '2026-12-15',
    lastMaintenanceDate: '2026-01-15',
    nextMaintenanceDate: '2026-07-15',
    maintenanceFrequency: 'bi-annually',
    notes: 'Premium developer machine assigned to Lead Systems Architect.',
    ipAddress: '192.168.20.45',
    mailType: 'EXTERNAL',
    usb: 'ALLOW',
    emailAddress: 'sarah.connor@cyberdyne.co'
  },
  {
    id: 'AST-2026-1002',
    type: 'laptop',
    name: 'ThinkPad T14s Gen 4',
    serialNumber: 'PF4X98A1',
    brand: 'Lenovo',
    model: 'AMD Ryzen 7 / 32GB / 1TB',
    os: 'Windows 11 Pro',
    purchaseDate: '2026-02-10',
    purchaseCost: 1450.00,
    department: 'HR',
    location: 'Chicago Hub - Office 302',
    status: 'available',
    assignedTo: null,
    assignedEmail: null,
    assignedDate: null,
    expectedReturnDate: null,
    lastMaintenanceDate: '2026-02-10',
    nextMaintenanceDate: '2026-08-10',
    maintenanceFrequency: 'bi-annually',
    notes: 'Standard HR laptop. Recently re-imaged and updated.',
    ipAddress: '192.168.10.15',
    mailType: 'INTERNAL',
    usb: 'ALLOW',
    emailAddress: 'chicago.hr@cyberdyne.com'
  },
  {
    id: 'AST-2026-1003',
    type: 'server',
    name: 'PowerEdge R760 Rack Server',
    serialNumber: '4XJ9082AA',
    brand: 'Dell',
    model: '2x Xeon Gold / 512GB / 16TB SW-RAID',
    os: 'Red Hat Enterprise Linux 9.3',
    purchaseDate: '2025-06-20',
    purchaseCost: 8990.00,
    department: 'IT',
    location: 'Ashburn Data Center - Rack B-04',
    status: 'checked-out',
    assignedTo: 'Linus Torvalds',
    assignedEmail: 'linus.t@kernelorg.net',
    assignedDate: '2025-06-22',
    expectedReturnDate: '2027-06-22',
    lastMaintenanceDate: '2026-02-15',
    nextMaintenanceDate: '2026-05-15', // Overdue maintenance alert! (Today is May 31, 2026)
    maintenanceFrequency: 'quarterly',
    notes: 'Production database backup host. Requires physical disk check & OS patching.',
    ipAddress: '10.0.4.11',
    mailType: 'GROUP',
    usb: 'BLOCK'
  },
  {
    id: 'AST-2026-1004',
    type: 'switch',
    name: 'Catalyst 9300 48-Port Switch',
    serialNumber: 'FCW2215D09Z',
    brand: 'Cisco',
    model: 'C9300-48UXM-A',
    os: 'Cisco IOS-XE 17.9.4',
    purchaseDate: '2025-08-11',
    purchaseCost: 4200.00,
    department: 'IT',
    location: 'SF HQ - Server Closet Room 12',
    status: 'available',
    assignedTo: null,
    assignedEmail: null,
    assignedDate: null,
    expectedReturnDate: null,
    lastMaintenanceDate: '2025-08-11',
    nextMaintenanceDate: '2026-08-11',
    maintenanceFrequency: 'annually',
    notes: 'Core switch for Level 2 office network backbone.',
    ipAddress: '10.100.1.1',
    mailType: 'NIL',
    usb: 'BLOCK'
  },
  {
    id: 'AST-2026-1005',
    type: 'printer',
    name: 'LaserJet Enterprise M608dn',
    serialNumber: 'JPGRF90123',
    brand: 'HP',
    model: 'M608dn Mono Laser',
    os: 'HP FutureSmart Firmware v4.11',
    purchaseDate: '2024-11-05',
    purchaseCost: 1199.00,
    department: 'Operations',
    location: 'SF HQ - Floor 3 Mailroom',
    status: 'maintenance',
    assignedTo: null,
    assignedEmail: null,
    assignedDate: null,
    expectedReturnDate: null,
    lastMaintenanceDate: '2026-03-10',
    nextMaintenanceDate: '2026-06-10',
    maintenanceFrequency: 'quarterly',
    notes: 'Experiencing paper jams in tray 2. Roller replacement kit on order.',
    ipAddress: '192.168.1.18',
    mailType: 'NIL',
    usb: 'BLOCK'
  },
  {
    id: 'AST-2026-1006',
    type: 'desktop',
    name: 'EliteDesk 800 G9 Tower',
    serialNumber: 'MXL40410BZ',
    brand: 'HP',
    model: 'Core i9 / 64GB / 1TB SSD',
    os: 'Windows 11 Enterprise (LTSC)',
    purchaseDate: '2025-03-14',
    purchaseCost: 1850.00,
    department: 'Finance',
    location: 'Chicago Hub - Desk 312',
    status: 'checked-out',
    assignedTo: 'Clark Kent',
    assignedEmail: 'clark.kent@dailyplanet.com',
    assignedDate: '2025-03-20',
    expectedReturnDate: '2026-07-31',
    lastMaintenanceDate: '2025-09-20',
    nextMaintenanceDate: '2026-03-20', // Overdue maintenance alert!
    maintenanceFrequency: 'bi-annually',
    notes: 'Assigned for complex Excel modeling and financial reporting.',
    ipAddress: '192.168.10.82',
    mailType: 'INTERNAL',
    usb: 'ALLOW'
  },
  {
    id: 'AST-2026-1007',
    type: 'server',
    name: 'ProLiant DL380 Gen11',
    serialNumber: 'SGH51299XX',
    brand: 'HPE',
    model: 'Gen11 / Dual AMD 32-core / 256GB / 8TB SSD',
    os: 'VMware ESXi 8.0u2',
    purchaseDate: '2025-09-01',
    purchaseCost: 7500.00,
    department: 'Engineering',
    location: 'Ashburn Data Center - Rack C-01',
    status: 'maintenance',
    assignedTo: null,
    assignedEmail: null,
    assignedDate: null,
    expectedReturnDate: null,
    lastMaintenanceDate: '2025-09-01',
    nextMaintenanceDate: '2026-03-01', // Maintenance overdue + currently in maintenance status!
    maintenanceFrequency: 'bi-annually',
    notes: 'Hypervisor host. Thermal warnings on CPU-2. Heat pipe replacement scheduled.',
    ipAddress: '10.0.1.100',
    mailType: 'NIL',
    usb: 'BLOCK'
  },
  {
    id: 'AST-2026-1008',
    type: 'laptop',
    name: 'Latitude 7440 Ultrabook',
    serialNumber: '9ZX12V4',
    brand: 'Dell',
    model: 'Core i7 / 16GB / 512GB',
    os: 'Windows 11 Pro',
    purchaseDate: '2026-01-22',
    purchaseCost: 1299.00,
    department: 'Sales',
    location: 'Remote - New York',
    status: 'checked-out',
    assignedTo: 'Diana Prince',
    assignedEmail: 'diana.prince@themyscira.gov',
    assignedDate: '2026-01-25',
    expectedReturnDate: '2026-05-20', // Overdue return alert! (Returned past expected date)
    lastMaintenanceDate: '2026-01-22',
    nextMaintenanceDate: '2026-07-22',
    maintenanceFrequency: 'bi-annually',
    notes: 'Sales demo laptop. Currently traveling.',
    ipAddress: '192.168.4.120',
    mailType: 'EXTERNAL',
    usb: 'ALLOW'
  },
  {
    id: 'AST-2026-1009',
    type: 'peripheral',
    name: 'UltraSharp 34" Curved Monitor',
    serialNumber: 'CN-0WX89F-83921',
    brand: 'Dell',
    model: 'U3421WE USB-C Hub Monitor',
    os: 'Firmware v102',
    purchaseDate: '2025-04-10',
    purchaseCost: 650.00,
    department: 'Engineering',
    location: 'SF HQ - Desk 124',
    status: 'checked-out',
    assignedTo: 'Sarah Connor',
    assignedEmail: 'sarah.connor@cyberdyne.co',
    assignedDate: '2026-01-16',
    expectedReturnDate: '2026-12-15',
    lastMaintenanceDate: '2025-04-10',
    nextMaintenanceDate: '2026-04-10', // Overdue maintenance
    maintenanceFrequency: 'annually',
    notes: 'KVM setup paired with macOS laptop.',
    ipAddress: '—',
    mailType: 'NIL',
    usb: 'ALLOW'
  },
  {
    id: 'AST-2026-1010',
    type: 'router',
    name: 'Integrated ISR 4451 Router',
    serialNumber: 'SRX4451-92B',
    brand: 'Cisco',
    model: 'ISR 4451 / 16G RAM',
    os: 'Cisco IOS-XE 16.9',
    purchaseDate: '2025-05-12',
    purchaseCost: 3200.00,
    department: 'IT',
    location: 'SF HQ - Server Closet Room 12',
    status: 'available',
    assignedTo: null,
    assignedEmail: null,
    assignedDate: null,
    expectedReturnDate: null,
    lastMaintenanceDate: '2025-05-12',
    nextMaintenanceDate: '2026-05-12',
    maintenanceFrequency: 'annually',
    notes: 'Primary gateway router.',
    ipAddress: '10.254.254.1',
    mailType: 'NIL',
    usb: 'BLOCK'
  },
  {
    id: 'AST-2026-1011',
    type: 'firewall',
    name: 'Firepower 2130 Threat Defense',
    serialNumber: 'FP2130-99XLR',
    brand: 'Cisco',
    model: 'ASA 2130 Hardware',
    os: 'Cisco FTD v7.0',
    purchaseDate: '2025-09-02',
    purchaseCost: 9800.00,
    department: 'IT',
    location: 'SF HQ - Server Closet Room 12',
    status: 'available',
    assignedTo: null,
    assignedEmail: null,
    assignedDate: null,
    expectedReturnDate: null,
    lastMaintenanceDate: '2025-09-02',
    nextMaintenanceDate: '2026-09-02',
    maintenanceFrequency: 'annually',
    notes: 'Enterprise edge security appliance.',
    ipAddress: '10.254.254.2',
    mailType: 'NIL',
    usb: 'BLOCK'
  }
];

export const INITIAL_ASSIGNMENT_LOGS: AssignmentLog[] = [
  {
    id: 'AL-1001',
    assetId: 'AST-2026-1001',
    assetName: 'MacBook Pro 16"',
    assetType: 'laptop',
    action: 'check-out',
    employeeName: 'Sarah Connor',
    employeeEmail: 'sarah.connor@cyberdyne.co',
    department: 'Engineering',
    date: '2026-01-16 09:30',
    notes: 'Checked out initial developer laptop during on-boarding.'
  },
  {
    id: 'AL-1002',
    assetId: 'AST-2026-1002',
    assetName: 'ThinkPad T14s Gen 4',
    assetType: 'laptop',
    action: 'check-out',
    employeeName: 'John Connor',
    employeeEmail: 'john.connor@cyberdyne.co',
    department: 'Operations',
    date: '2026-02-15 10:15',
    notes: 'Temporary check-out for warehouse inventory systems.'
  },
  {
    id: 'AL-1003',
    assetId: 'AST-2026-1002',
    assetName: 'ThinkPad T14s Gen 4',
    assetType: 'laptop',
    action: 'check-in',
    employeeName: 'John Connor',
    employeeEmail: 'john.connor@cyberdyne.co',
    department: 'Operations',
    date: '2026-02-28 16:45',
    notes: 'Asset returned. Cleaned and prepared for next assignment.'
  },
  {
    id: 'AL-1004',
    assetId: 'AST-2026-1003',
    assetName: 'PowerEdge R760 Rack Server',
    assetType: 'server',
    action: 'check-out',
    employeeName: 'Linus Torvalds',
    employeeEmail: 'linus.t@kernelorg.net',
    department: 'IT',
    date: '2025-06-22 14:00',
    notes: 'Server provisioned and handed over for kernel testing & virtualization clusters.'
  },
  {
    id: 'AL-1005',
    assetId: 'AST-2026-1006',
    assetName: 'EliteDesk 800 G9 Tower',
    assetType: 'desktop',
    action: 'check-out',
    employeeName: 'Clark Kent',
    employeeEmail: 'clark.kent@dailyplanet.com',
    department: 'Finance',
    date: '2025-03-20 08:30',
    notes: 'Workstation assigned for core finance duties.'
  },
  {
    id: 'AL-1006',
    assetId: 'AST-2026-1008',
    assetName: 'Latitude 7440 Ultrabook',
    assetType: 'laptop',
    action: 'check-out',
    employeeName: 'Diana Prince',
    employeeEmail: 'diana.prince@themyscira.gov',
    department: 'Sales',
    date: '2026-01-25 11:00',
    notes: 'Sales traveling kit with charger and adaptors.'
  },
  {
    id: 'AL-1007',
    assetId: 'AST-2026-1009',
    assetName: 'UltraSharp 34" Curved Monitor',
    assetType: 'peripheral',
    action: 'check-out',
    employeeName: 'Sarah Connor',
    employeeEmail: 'sarah.connor@cyberdyne.co',
    department: 'Engineering',
    date: '2026-01-16 10:15',
    notes: 'Secondary monitor for lead architect setup.'
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'AUD-001',
    timestamp: '2026-05-30T10:12:00Z',
    action: 'Asset Updated',
    details: 'Asset AST-2026-1005 (LaserJet Printer) status changed to [maintenance]. Note added: experiencing jams.',
    category: 'update',
    user: 'saravananengineerit@gmail.com'
  },
  {
    id: 'AUD-002',
    timestamp: '2026-05-29T15:45:00Z',
    action: 'Maintenance Scheduled',
    details: 'Routine bios flash and fan dust cleaning scheduled for DL380 database server (AST-2026-1007).',
    category: 'maintenance',
    user: 'saravananengineerit@gmail.com'
  },
  {
    id: 'AUD-003',
    timestamp: '2026-05-28T09:15:00Z',
    action: 'Asset Checked In',
    details: 'Asset AST-2026-1002 checked in from John Connor (Operations) to IT Depot.',
    category: 'check-in',
    user: 'saravananengineerit@gmail.com'
  },
  {
    id: 'AUD-004',
    timestamp: '2026-05-28T08:50:00Z',
    action: 'Asset Created',
    details: 'New record AST-2026-1008 (Dell Latitude 7440) created for Sales onboarding.',
    category: 'create',
    user: 'saravananengineerit@gmail.com'
  },
  {
    id: 'AUD-005',
    timestamp: '2026-05-20T14:30:00Z',
    action: 'Asset Checked Out',
    details: 'New MacBook Pro 16" (AST-2026-1001) checked out to Sarah Connor (Engineering).',
    category: 'check-out',
    user: 'saravananengineerit@gmail.com'
  }
];

export const INITIAL_MAINTENANCE_RECORDS: MaintenanceRecord[] = [
  {
    id: 'MR-001',
    assetId: 'AST-2026-1003',
    assetName: 'PowerEdge R760 Rack Server',
    date: '2026-02-15',
    performer: 'Linus Torvalds (Self)',
    type: 'routine',
    cost: 0.00,
    details: 'Kernel security patch update applied. RAID consistency check ran cleanly.',
    outcome: 'resolved'
  },
  {
    id: 'MR-002',
    assetId: 'AST-2026-1005',
    assetName: 'LaserJet Enterprise M608dn',
    date: '2026-03-10',
    performer: 'HP Support (Contract)',
    type: 'repair',
    cost: 150.00,
    details: 'Replaced rollers in tray 1. Roller wear detected on secondary trays.',
    outcome: 'resolved'
  },
  {
    id: 'MR-003',
    assetId: 'AST-2026-1006',
    assetName: 'EliteDesk 800 G9 Tower',
    date: '2025-09-20',
    performer: 'Internal IT Desk',
    type: 'upgrade',
    cost: 85.00,
    details: 'RAM upgraded from 32GB to 64GB to support high-scale model execution queries.',
    outcome: 'resolved'
  },
  {
    id: 'MR-004',
    assetId: 'AST-2026-1007',
    assetName: 'ProLiant DL380 Gen11',
    date: '2025-09-01',
    performer: 'HP Engineering',
    type: 'calibration',
    cost: 450.00,
    details: 'Initial rack install, burn-in diagnostics, OS hypervisor deployment validation.',
    outcome: 'resolved'
  }
];
